apiVersion: v1
kind: Secret
metadata:
  name: cuepoint-secrets
  namespace: default
type: Opaque
data:
  # Echo -n "value" | base64
  database-url: cG9zdGdyZXNxbDovL3VzZXI6cGFzc3dvcmRAcG9zdGdyZXMtc2VydmljZTo1NDMyL2N1ZXBvaW50 # postgresql://user:password@postgres-service:5432/cuepoint
  redis-url: cmVkaXM6Ly9yZWRpcy1zZXJ2aWNlOjYzNzkvMA== # redis://redis-service:6379/0
  minio-access-key: bWluaW9hZG1pbg== # minioadmin
  minio-secret-key: bWluaW9hZG1pbg== # minioadmin
